### ISSUE TITLE
Tugger startup error

### ISSUE THREAD

**Issue by loicalbertin** [jainishshah17/tugger#189]
Hi,

I'm running on MicroK8S (v1.27.4)

Starting with Tugger tag 324 and newer, Tugger fails to start with the following messages:

```
/tugger: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tugger)
/tugger: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tugger)
```

Did I miss something?

**Comment by kd7lxl** [comment]
It has been a while since the set of Kubernetes versions exercised in the tests have been updated. That would be the first step in trying to reproduce this. If you want to open a PR for it, that would be appreciated.

https://github.com/jainishshah17/tugger/blob/7dacca710dedcc431f458bb63d6b553fe8b59261/.github/workflows/pr.yaml#L28-L32

**Comment by kd7lxl** [comment]
#187 sounds related. Maybe that will help you.

I was not able to reproduce this in Kubernetes v1.27 in #190. It's working fine there, both with and without the change in #187.

**Comment by loicalbertin** [comment]
Problem solved with tag 344.
Thanks!
